# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T10:11:15+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel, constr


class AdditionalDeploymentStatusInfo(RootModel[str]):
    root: str = Field(
        ...,
        description='AdditionalDeploymentStatusInfo is deprecated, use DeploymentStatusMessageList instead.',
    )


class AlarmName(RootModel[str]):
    root: str


class AlarmsLimitExceededException(RootModel[Any]):
    root: Any


class ApplicationAlreadyExistsException(RootModel[Any]):
    root: Any


class ApplicationDoesNotExistException(RootModel[Any]):
    root: Any


class ApplicationId(RootModel[str]):
    root: str


class ApplicationLimitExceededException(RootModel[Any]):
    root: Any


class ApplicationName(RootModel[constr(min_length=1, max_length=100)]):
    root: constr(min_length=1, max_length=100)


class ApplicationNameRequiredException(RootModel[Any]):
    root: Any


class ApplicationRevisionSortBy(Enum):
    registerTime = 'registerTime'
    firstUsedTime = 'firstUsedTime'
    lastUsedTime = 'lastUsedTime'


class ApplicationsList(RootModel[List[ApplicationName]]):
    root: List[ApplicationName]


class Arn(RootModel[constr(min_length=1, max_length=1011)]):
    root: constr(min_length=1, max_length=1011)


class ArnNotSupportedException(RootModel[Any]):
    root: Any


class AutoRollbackEvent(Enum):
    DEPLOYMENT_FAILURE = 'DEPLOYMENT_FAILURE'
    DEPLOYMENT_STOP_ON_ALARM = 'DEPLOYMENT_STOP_ON_ALARM'
    DEPLOYMENT_STOP_ON_REQUEST = 'DEPLOYMENT_STOP_ON_REQUEST'


class AutoRollbackEventsList(RootModel[List[AutoRollbackEvent]]):
    root: List[AutoRollbackEvent]


class AutoScalingGroupHook(RootModel[str]):
    root: str


class AutoScalingGroupName(RootModel[str]):
    root: str


class AutoScalingGroupNameList(RootModel[List[AutoScalingGroupName]]):
    root: List[AutoScalingGroupName]


class BatchGetApplicationsInput(BaseModel):
    applicationNames: ApplicationsList


class BatchLimitExceededException(RootModel[Any]):
    root: Any


class Boolean(RootModel[bool]):
    root: bool


class BucketNameFilterRequiredException(RootModel[Any]):
    root: Any


class BundleType(Enum):
    tar = 'tar'
    tgz = 'tgz'
    zip = 'zip'
    YAML = 'YAML'
    JSON = 'JSON'


class CloudFormationResourceType(RootModel[str]):
    root: str


class CommitId(RootModel[str]):
    root: str


class ComputePlatform(Enum):
    Server = 'Server'
    Lambda = 'Lambda'
    ECS = 'ECS'


class CreateApplicationOutput(BaseModel):
    applicationId: Optional[ApplicationId] = None


class DeleteApplicationInput(BaseModel):
    applicationName: ApplicationName


class DeleteResourcesByExternalIdOutput(BaseModel):
    pass


class DeploymentAlreadyCompletedException(RootModel[Any]):
    root: Any


class DeploymentConfigAlreadyExistsException(RootModel[Any]):
    root: Any


class DeploymentConfigDoesNotExistException(RootModel[Any]):
    root: Any


class DeploymentConfigId(RootModel[str]):
    root: str


class DeploymentConfigInUseException(RootModel[Any]):
    root: Any


class DeploymentConfigLimitExceededException(RootModel[Any]):
    root: Any


class DeploymentConfigName(RootModel[constr(min_length=1, max_length=100)]):
    root: constr(min_length=1, max_length=100)


class DeploymentConfigNameRequiredException(RootModel[Any]):
    root: Any


class DeploymentConfigsList(RootModel[List[DeploymentConfigName]]):
    root: List[DeploymentConfigName]


class DeploymentCreator(Enum):
    user = 'user'
    autoscaling = 'autoscaling'
    codeDeployRollback = 'codeDeployRollback'
    CodeDeploy = 'CodeDeploy'
    CodeDeployAutoUpdate = 'CodeDeployAutoUpdate'
    CloudFormation = 'CloudFormation'
    CloudFormationRollback = 'CloudFormationRollback'


class DeploymentDoesNotExistException(RootModel[Any]):
    root: Any


class DeploymentGroupAlreadyExistsException(RootModel[Any]):
    root: Any


class DeploymentGroupDoesNotExistException(RootModel[Any]):
    root: Any


class DeploymentGroupId(RootModel[str]):
    root: str


class DeploymentGroupLimitExceededException(RootModel[Any]):
    root: Any


class DeploymentGroupName(RootModel[constr(min_length=1, max_length=100)]):
    root: constr(min_length=1, max_length=100)


class DeploymentGroupNameRequiredException(RootModel[Any]):
    root: Any


class DeploymentGroupsList(RootModel[List[DeploymentGroupName]]):
    root: List[DeploymentGroupName]


class DeploymentId(RootModel[str]):
    root: str


class DeploymentIdRequiredException(RootModel[Any]):
    root: Any


class DeploymentIsNotInReadyStateException(RootModel[Any]):
    root: Any


class DeploymentLimitExceededException(RootModel[Any]):
    root: Any


class DeploymentNotStartedException(RootModel[Any]):
    root: Any


class DeploymentOption(Enum):
    WITH_TRAFFIC_CONTROL = 'WITH_TRAFFIC_CONTROL'
    WITHOUT_TRAFFIC_CONTROL = 'WITHOUT_TRAFFIC_CONTROL'


class DeploymentReadyAction(Enum):
    CONTINUE_DEPLOYMENT = 'CONTINUE_DEPLOYMENT'
    STOP_DEPLOYMENT = 'STOP_DEPLOYMENT'


class DeploymentStatus(Enum):
    Created = 'Created'
    Queued = 'Queued'
    InProgress = 'InProgress'
    Baking = 'Baking'
    Succeeded = 'Succeeded'
    Failed = 'Failed'
    Stopped = 'Stopped'
    Ready = 'Ready'


class DeploymentStatusList(RootModel[List[DeploymentStatus]]):
    root: List[DeploymentStatus]


class DeploymentTargetDoesNotExistException(RootModel[Any]):
    root: Any


class DeploymentTargetIdRequiredException(RootModel[Any]):
    root: Any


class DeploymentTargetListSizeExceededException(RootModel[Any]):
    root: Any


class DeploymentTargetType(Enum):
    InstanceTarget = 'InstanceTarget'
    LambdaTarget = 'LambdaTarget'
    ECSTarget = 'ECSTarget'
    CloudFormationTarget = 'CloudFormationTarget'


class DeploymentType(Enum):
    IN_PLACE = 'IN_PLACE'
    BLUE_GREEN = 'BLUE_GREEN'


class DeploymentWaitType(Enum):
    READY_WAIT = 'READY_WAIT'
    TERMINATION_WAIT = 'TERMINATION_WAIT'


class DeploymentsList(RootModel[List[DeploymentId]]):
    root: List[DeploymentId]


class Description(RootModel[str]):
    root: str


class DescriptionTooLongException(RootModel[Any]):
    root: Any


class Duration(RootModel[int]):
    root: int


class EC2TagFilterType(Enum):
    KEY_ONLY = 'KEY_ONLY'
    VALUE_ONLY = 'VALUE_ONLY'
    KEY_AND_VALUE = 'KEY_AND_VALUE'


class ECSClusterName(RootModel[str]):
    root: str


class ECSServiceMappingLimitExceededException(RootModel[Any]):
    root: Any


class ECSServiceName(RootModel[str]):
    root: str


class ECSTaskSetCount(RootModel[int]):
    root: int


class ECSTaskSetIdentifier(RootModel[str]):
    root: str


class ECSTaskSetStatus(RootModel[str]):
    root: str


class ELBName(RootModel[str]):
    root: str


class ETag(RootModel[str]):
    root: str


class ErrorCode(Enum):
    AGENT_ISSUE = 'AGENT_ISSUE'
    ALARM_ACTIVE = 'ALARM_ACTIVE'
    APPLICATION_MISSING = 'APPLICATION_MISSING'
    AUTOSCALING_VALIDATION_ERROR = 'AUTOSCALING_VALIDATION_ERROR'
    AUTO_SCALING_CONFIGURATION = 'AUTO_SCALING_CONFIGURATION'
    AUTO_SCALING_IAM_ROLE_PERMISSIONS = 'AUTO_SCALING_IAM_ROLE_PERMISSIONS'
    CODEDEPLOY_RESOURCE_CANNOT_BE_FOUND = 'CODEDEPLOY_RESOURCE_CANNOT_BE_FOUND'
    CUSTOMER_APPLICATION_UNHEALTHY = 'CUSTOMER_APPLICATION_UNHEALTHY'
    DEPLOYMENT_GROUP_MISSING = 'DEPLOYMENT_GROUP_MISSING'
    ECS_UPDATE_ERROR = 'ECS_UPDATE_ERROR'
    ELASTIC_LOAD_BALANCING_INVALID = 'ELASTIC_LOAD_BALANCING_INVALID'
    ELB_INVALID_INSTANCE = 'ELB_INVALID_INSTANCE'
    HEALTH_CONSTRAINTS = 'HEALTH_CONSTRAINTS'
    HEALTH_CONSTRAINTS_INVALID = 'HEALTH_CONSTRAINTS_INVALID'
    HOOK_EXECUTION_FAILURE = 'HOOK_EXECUTION_FAILURE'
    IAM_ROLE_MISSING = 'IAM_ROLE_MISSING'
    IAM_ROLE_PERMISSIONS = 'IAM_ROLE_PERMISSIONS'
    INTERNAL_ERROR = 'INTERNAL_ERROR'
    INVALID_ECS_SERVICE = 'INVALID_ECS_SERVICE'
    INVALID_LAMBDA_CONFIGURATION = 'INVALID_LAMBDA_CONFIGURATION'
    INVALID_LAMBDA_FUNCTION = 'INVALID_LAMBDA_FUNCTION'
    INVALID_REVISION = 'INVALID_REVISION'
    MANUAL_STOP = 'MANUAL_STOP'
    MISSING_BLUE_GREEN_DEPLOYMENT_CONFIGURATION = (
        'MISSING_BLUE_GREEN_DEPLOYMENT_CONFIGURATION'
    )
    MISSING_ELB_INFORMATION = 'MISSING_ELB_INFORMATION'
    MISSING_GITHUB_TOKEN = 'MISSING_GITHUB_TOKEN'
    NO_EC2_SUBSCRIPTION = 'NO_EC2_SUBSCRIPTION'
    NO_INSTANCES = 'NO_INSTANCES'
    OVER_MAX_INSTANCES = 'OVER_MAX_INSTANCES'
    RESOURCE_LIMIT_EXCEEDED = 'RESOURCE_LIMIT_EXCEEDED'
    REVISION_MISSING = 'REVISION_MISSING'
    THROTTLED = 'THROTTLED'
    TIMEOUT = 'TIMEOUT'
    CLOUDFORMATION_STACK_FAILURE = 'CLOUDFORMATION_STACK_FAILURE'


class ErrorMessage(RootModel[str]):
    root: str


class ExternalId(RootModel[str]):
    root: str


class FileExistsBehavior(Enum):
    DISALLOW = 'DISALLOW'
    OVERWRITE = 'OVERWRITE'
    RETAIN = 'RETAIN'


class FilterValue(RootModel[str]):
    root: str


class FilterValueList(RootModel[List[FilterValue]]):
    root: List[FilterValue]


class GetApplicationInput(BaseModel):
    applicationName: ApplicationName


class GetDeploymentConfigInput(BaseModel):
    deploymentConfigName: DeploymentConfigName


class GetDeploymentGroupInput(BaseModel):
    applicationName: ApplicationName
    deploymentGroupName: DeploymentGroupName


class GetDeploymentInput(BaseModel):
    deploymentId: DeploymentId


class GitHubAccountTokenDoesNotExistException(RootModel[Any]):
    root: Any


class GitHubAccountTokenName(RootModel[str]):
    root: str


class GitHubAccountTokenNameList(RootModel[List[GitHubAccountTokenName]]):
    root: List[GitHubAccountTokenName]


class GitHubAccountTokenNameRequiredException(RootModel[Any]):
    root: Any


class GreenFleetProvisioningAction(Enum):
    DISCOVER_EXISTING = 'DISCOVER_EXISTING'
    COPY_AUTO_SCALING_GROUP = 'COPY_AUTO_SCALING_GROUP'


class GreenFleetProvisioningOption(BaseModel):
    action: Optional[GreenFleetProvisioningAction] = None


class IamArnRequiredException(RootModel[Any]):
    root: Any


class IamSessionArn(RootModel[str]):
    root: str


class IamSessionArnAlreadyRegisteredException(RootModel[Any]):
    root: Any


class IamUserArn(RootModel[str]):
    root: str


class IamUserArnAlreadyRegisteredException(RootModel[Any]):
    root: Any


class IamUserArnRequiredException(RootModel[Any]):
    root: Any


class InstanceAction(Enum):
    TERMINATE = 'TERMINATE'
    KEEP_ALIVE = 'KEEP_ALIVE'


class InstanceArn(RootModel[str]):
    root: str


class InstanceCount(RootModel[int]):
    root: int


class InstanceDoesNotExistException(RootModel[Any]):
    root: Any


class InstanceId(RootModel[str]):
    root: str


class InstanceIdRequiredException(RootModel[Any]):
    root: Any


class InstanceLimitExceededException(RootModel[Any]):
    root: Any


class InstanceName(RootModel[str]):
    root: str


class InstanceNameAlreadyRegisteredException(RootModel[Any]):
    root: Any


class InstanceNameList(RootModel[List[InstanceName]]):
    root: List[InstanceName]


class InstanceNameRequiredException(RootModel[Any]):
    root: Any


class InstanceNotRegisteredException(RootModel[Any]):
    root: Any


class InstanceStatus(Enum):
    Pending = 'Pending'
    InProgress = 'InProgress'
    Succeeded = 'Succeeded'
    Failed = 'Failed'
    Skipped = 'Skipped'
    Unknown = 'Unknown'
    Ready = 'Ready'


class InstanceStatusList(RootModel[List[InstanceStatus]]):
    root: List[InstanceStatus]


class InstanceType(Enum):
    Blue = 'Blue'
    Green = 'Green'


class InstanceTypeList(RootModel[List[InstanceType]]):
    root: List[InstanceType]


class InstancesList(RootModel[List[InstanceId]]):
    root: List[InstanceId]


class InvalidAlarmConfigException(RootModel[Any]):
    root: Any


class InvalidApplicationNameException(RootModel[Any]):
    root: Any


class InvalidArnException(RootModel[Any]):
    root: Any


class InvalidAutoRollbackConfigException(RootModel[Any]):
    root: Any


class InvalidAutoScalingGroupException(RootModel[Any]):
    root: Any


class InvalidBlueGreenDeploymentConfigurationException(RootModel[Any]):
    root: Any


class InvalidBucketNameFilterException(RootModel[Any]):
    root: Any


class InvalidComputePlatformException(RootModel[Any]):
    root: Any


class InvalidDeployedStateFilterException(RootModel[Any]):
    root: Any


class InvalidDeploymentConfigNameException(RootModel[Any]):
    root: Any


class InvalidDeploymentGroupNameException(RootModel[Any]):
    root: Any


class InvalidDeploymentIdException(RootModel[Any]):
    root: Any


class InvalidDeploymentInstanceTypeException(RootModel[Any]):
    root: Any


class InvalidDeploymentStatusException(RootModel[Any]):
    root: Any


class InvalidDeploymentStyleException(RootModel[Any]):
    root: Any


class InvalidDeploymentTargetIdException(RootModel[Any]):
    root: Any


class InvalidDeploymentWaitTypeException(RootModel[Any]):
    root: Any


class InvalidEC2TagCombinationException(RootModel[Any]):
    root: Any


class InvalidEC2TagException(RootModel[Any]):
    root: Any


class InvalidECSServiceException(RootModel[Any]):
    root: Any


class InvalidExternalIdException(RootModel[Any]):
    root: Any


class InvalidFileExistsBehaviorException(RootModel[Any]):
    root: Any


class InvalidGitHubAccountTokenException(RootModel[Any]):
    root: Any


class InvalidGitHubAccountTokenNameException(RootModel[Any]):
    root: Any


class InvalidIamSessionArnException(RootModel[Any]):
    root: Any


class InvalidIamUserArnException(RootModel[Any]):
    root: Any


class InvalidIgnoreApplicationStopFailuresValueException(RootModel[Any]):
    root: Any


class InvalidInputException(RootModel[Any]):
    root: Any


class InvalidInstanceNameException(RootModel[Any]):
    root: Any


class InvalidInstanceStatusException(RootModel[Any]):
    root: Any


class InvalidInstanceTypeException(RootModel[Any]):
    root: Any


class InvalidKeyPrefixFilterException(RootModel[Any]):
    root: Any


class InvalidLifecycleEventHookExecutionIdException(RootModel[Any]):
    root: Any


class InvalidLifecycleEventHookExecutionStatusException(RootModel[Any]):
    root: Any


class InvalidLoadBalancerInfoException(RootModel[Any]):
    root: Any


class InvalidMinimumHealthyHostValueException(RootModel[Any]):
    root: Any


class InvalidNextTokenException(RootModel[Any]):
    root: Any


class InvalidOnPremisesTagCombinationException(RootModel[Any]):
    root: Any


class InvalidOperationException(RootModel[Any]):
    root: Any


class InvalidRegistrationStatusException(RootModel[Any]):
    root: Any


class InvalidRevisionException(RootModel[Any]):
    root: Any


class InvalidRoleException(RootModel[Any]):
    root: Any


class InvalidSortByException(RootModel[Any]):
    root: Any


class InvalidSortOrderException(RootModel[Any]):
    root: Any


class InvalidTagException(RootModel[Any]):
    root: Any


class InvalidTagFilterException(RootModel[Any]):
    root: Any


class InvalidTagsToAddException(RootModel[Any]):
    root: Any


class InvalidTargetFilterNameException(RootModel[Any]):
    root: Any


class InvalidTargetGroupPairException(RootModel[Any]):
    root: Any


class InvalidTargetInstancesException(RootModel[Any]):
    root: Any


class InvalidTimeRangeException(RootModel[Any]):
    root: Any


class InvalidTrafficRoutingConfigurationException(RootModel[Any]):
    root: Any


class InvalidTriggerConfigException(RootModel[Any]):
    root: Any


class InvalidUpdateOutdatedInstancesOnlyValueException(RootModel[Any]):
    root: Any


class Key(RootModel[str]):
    root: str


class LambdaFunctionAlias(RootModel[str]):
    root: str


class LambdaFunctionName(RootModel[str]):
    root: str


class LifecycleErrorCode(Enum):
    Success = 'Success'
    ScriptMissing = 'ScriptMissing'
    ScriptNotExecutable = 'ScriptNotExecutable'
    ScriptTimedOut = 'ScriptTimedOut'
    ScriptFailed = 'ScriptFailed'
    UnknownError = 'UnknownError'


class LifecycleEventAlreadyCompletedException(RootModel[Any]):
    root: Any


class LifecycleEventHookExecutionId(RootModel[str]):
    root: str


class LifecycleEventName(RootModel[str]):
    root: str


class LifecycleEventStatus(Enum):
    Pending = 'Pending'
    InProgress = 'InProgress'
    Succeeded = 'Succeeded'
    Failed = 'Failed'
    Skipped = 'Skipped'
    Unknown = 'Unknown'


class LifecycleHookLimitExceededException(RootModel[Any]):
    root: Any


class LifecycleMessage(RootModel[str]):
    root: str


class ListStateFilterAction(Enum):
    include = 'include'
    exclude = 'exclude'
    ignore = 'ignore'


class ListenerArn(RootModel[str]):
    root: str


class ListenerArnList(RootModel[List[ListenerArn]]):
    root: List[ListenerArn]


class LogTail(RootModel[str]):
    root: str


class Message(RootModel[str]):
    root: str


class MinimumHealthyHostsType(Enum):
    HOST_COUNT = 'HOST_COUNT'
    FLEET_PERCENT = 'FLEET_PERCENT'


class MinimumHealthyHostsValue(RootModel[int]):
    root: int


class MultipleIamArnsProvidedException(RootModel[Any]):
    root: Any


class NextToken(RootModel[str]):
    root: str


class NullableBoolean(RootModel[bool]):
    root: bool


class OperationNotSupportedException(RootModel[Any]):
    root: Any


class OutdatedInstancesStrategy(Enum):
    UPDATE = 'UPDATE'
    IGNORE = 'IGNORE'


class Percentage(RootModel[int]):
    root: int


class PutLifecycleEventHookExecutionStatusInput(BaseModel):
    deploymentId: Optional[DeploymentId] = None
    lifecycleEventHookExecutionId: Optional[LifecycleEventHookExecutionId] = None
    status: Optional[LifecycleEventStatus] = None


class PutLifecycleEventHookExecutionStatusOutput(BaseModel):
    lifecycleEventHookExecutionId: Optional[LifecycleEventHookExecutionId] = None


class RawStringContent(RootModel[str]):
    root: str


class RawStringSha256(RootModel[str]):
    root: str


class RegisterOnPremisesInstanceInput(BaseModel):
    iamSessionArn: Optional[IamSessionArn] = None
    iamUserArn: Optional[IamUserArn] = None
    instanceName: InstanceName


class RegistrationStatus(Enum):
    Registered = 'Registered'
    Deregistered = 'Deregistered'


class RelatedDeployments(BaseModel):
    autoUpdateOutdatedInstancesDeploymentIds: Optional[DeploymentsList] = None
    autoUpdateOutdatedInstancesRootDeploymentId: Optional[DeploymentId] = None


class Repository(RootModel[str]):
    root: str


class ResourceArnRequiredException(RootModel[Any]):
    root: Any


class ResourceValidationException(RootModel[Any]):
    root: Any


class RevisionDoesNotExistException(RootModel[Any]):
    root: Any


class RevisionLocationType(Enum):
    S3 = 'S3'
    GitHub = 'GitHub'
    String = 'String'
    AppSpecContent = 'AppSpecContent'


class RevisionRequiredException(RootModel[Any]):
    root: Any


class Role(RootModel[str]):
    root: str


class RoleRequiredException(RootModel[Any]):
    root: Any


class RollbackInfo(BaseModel):
    rollbackDeploymentId: Optional[DeploymentId] = None
    rollbackMessage: Optional[Description] = None
    rollbackTriggeringDeploymentId: Optional[DeploymentId] = None


class S3Bucket(RootModel[str]):
    root: str


class S3Key(RootModel[str]):
    root: str


class ScriptName(RootModel[str]):
    root: str


class SkipWaitTimeForInstanceTerminationInput(BaseModel):
    deploymentId: Optional[DeploymentId] = None


class SortOrder(Enum):
    ascending = 'ascending'
    descending = 'descending'


class StopDeploymentInput(BaseModel):
    autoRollbackEnabled: Optional[NullableBoolean] = None
    deploymentId: DeploymentId


class StopStatus(Enum):
    Pending = 'Pending'
    Succeeded = 'Succeeded'


class TagFilterType(Enum):
    KEY_ONLY = 'KEY_ONLY'
    VALUE_ONLY = 'VALUE_ONLY'
    KEY_AND_VALUE = 'KEY_AND_VALUE'


class TagKeyList(RootModel[List[Key]]):
    root: List[Key]


class TagLimitExceededException(RootModel[Any]):
    root: Any


class TagRequiredException(RootModel[Any]):
    root: Any


class TagResourceOutput(BaseModel):
    pass


class TagSetListLimitExceededException(RootModel[Any]):
    root: Any


class TargetArn(RootModel[str]):
    root: str


class TargetFilterName(Enum):
    TargetStatus = 'TargetStatus'
    ServerInstanceLabel = 'ServerInstanceLabel'


class TargetFilters(RootModel[Optional[Dict[str, FilterValueList]]]):
    root: Optional[Dict[str, FilterValueList]] = None


class TargetGroupName(RootModel[str]):
    root: str


class TargetId(RootModel[str]):
    root: str


class TargetIdList(RootModel[List[TargetId]]):
    root: List[TargetId]


class TargetLabel(Enum):
    Blue = 'Blue'
    Green = 'Green'


class TargetStatus(Enum):
    Pending = 'Pending'
    InProgress = 'InProgress'
    Succeeded = 'Succeeded'
    Failed = 'Failed'
    Skipped = 'Skipped'
    Unknown = 'Unknown'
    Ready = 'Ready'


class ThrottlingException(RootModel[Any]):
    root: Any


class Time(RootModel[datetime]):
    root: datetime


class Timestamp(RootModel[datetime]):
    root: datetime


class TrafficRoute(BaseModel):
    listenerArns: Optional[ListenerArnList] = None


class TrafficRoutingType(Enum):
    TimeBasedCanary = 'TimeBasedCanary'
    TimeBasedLinear = 'TimeBasedLinear'
    AllAtOnce = 'AllAtOnce'


class TrafficWeight(RootModel[float]):
    root: float


class TriggerEventType(Enum):
    DeploymentStart = 'DeploymentStart'
    DeploymentSuccess = 'DeploymentSuccess'
    DeploymentFailure = 'DeploymentFailure'
    DeploymentStop = 'DeploymentStop'
    DeploymentRollback = 'DeploymentRollback'
    DeploymentReady = 'DeploymentReady'
    InstanceStart = 'InstanceStart'
    InstanceSuccess = 'InstanceSuccess'
    InstanceFailure = 'InstanceFailure'
    InstanceReady = 'InstanceReady'


class TriggerEventTypeList(RootModel[List[TriggerEventType]]):
    root: List[TriggerEventType]


class TriggerName(RootModel[str]):
    root: str


class TriggerTargetArn(RootModel[str]):
    root: str


class TriggerTargetsLimitExceededException(RootModel[Any]):
    root: Any


class UnsupportedActionForDeploymentTypeException(RootModel[Any]):
    root: Any


class UntagResourceInput(BaseModel):
    ResourceArn: Arn
    TagKeys: TagKeyList


class UntagResourceOutput(BaseModel):
    pass


class UpdateApplicationInput(BaseModel):
    applicationName: Optional[ApplicationName] = None
    newApplicationName: Optional[ApplicationName] = None


class Value(RootModel[str]):
    root: str


class Version(RootModel[str]):
    root: str


class VersionId(RootModel[str]):
    root: str


class WaitTimeInMins(RootModel[int]):
    root: int


class XAmzTarget(Enum):
    CodeDeploy_20141006_AddTagsToOnPremisesInstances = (
        'CodeDeploy_20141006.AddTagsToOnPremisesInstances'
    )


class XAmzTarget1(Enum):
    CodeDeploy_20141006_BatchGetApplicationRevisions = (
        'CodeDeploy_20141006.BatchGetApplicationRevisions'
    )


class XAmzTarget2(Enum):
    CodeDeploy_20141006_BatchGetApplications = (
        'CodeDeploy_20141006.BatchGetApplications'
    )


class XAmzTarget3(Enum):
    CodeDeploy_20141006_BatchGetDeploymentGroups = (
        'CodeDeploy_20141006.BatchGetDeploymentGroups'
    )


class XAmzTarget4(Enum):
    CodeDeploy_20141006_BatchGetDeploymentInstances = (
        'CodeDeploy_20141006.BatchGetDeploymentInstances'
    )


class XAmzTarget5(Enum):
    CodeDeploy_20141006_BatchGetDeploymentTargets = (
        'CodeDeploy_20141006.BatchGetDeploymentTargets'
    )


class XAmzTarget6(Enum):
    CodeDeploy_20141006_BatchGetDeployments = 'CodeDeploy_20141006.BatchGetDeployments'


class XAmzTarget7(Enum):
    CodeDeploy_20141006_BatchGetOnPremisesInstances = (
        'CodeDeploy_20141006.BatchGetOnPremisesInstances'
    )


class XAmzTarget8(Enum):
    CodeDeploy_20141006_ContinueDeployment = 'CodeDeploy_20141006.ContinueDeployment'


class XAmzTarget9(Enum):
    CodeDeploy_20141006_CreateApplication = 'CodeDeploy_20141006.CreateApplication'


class XAmzTarget10(Enum):
    CodeDeploy_20141006_CreateDeployment = 'CodeDeploy_20141006.CreateDeployment'


class XAmzTarget11(Enum):
    CodeDeploy_20141006_CreateDeploymentConfig = (
        'CodeDeploy_20141006.CreateDeploymentConfig'
    )


class XAmzTarget12(Enum):
    CodeDeploy_20141006_CreateDeploymentGroup = (
        'CodeDeploy_20141006.CreateDeploymentGroup'
    )


class XAmzTarget13(Enum):
    CodeDeploy_20141006_DeleteApplication = 'CodeDeploy_20141006.DeleteApplication'


class XAmzTarget14(Enum):
    CodeDeploy_20141006_DeleteDeploymentConfig = (
        'CodeDeploy_20141006.DeleteDeploymentConfig'
    )


class XAmzTarget15(Enum):
    CodeDeploy_20141006_DeleteDeploymentGroup = (
        'CodeDeploy_20141006.DeleteDeploymentGroup'
    )


class XAmzTarget16(Enum):
    CodeDeploy_20141006_DeleteGitHubAccountToken = (
        'CodeDeploy_20141006.DeleteGitHubAccountToken'
    )


class XAmzTarget17(Enum):
    CodeDeploy_20141006_DeleteResourcesByExternalId = (
        'CodeDeploy_20141006.DeleteResourcesByExternalId'
    )


class XAmzTarget18(Enum):
    CodeDeploy_20141006_DeregisterOnPremisesInstance = (
        'CodeDeploy_20141006.DeregisterOnPremisesInstance'
    )


class XAmzTarget19(Enum):
    CodeDeploy_20141006_GetApplication = 'CodeDeploy_20141006.GetApplication'


class XAmzTarget20(Enum):
    CodeDeploy_20141006_GetApplicationRevision = (
        'CodeDeploy_20141006.GetApplicationRevision'
    )


class XAmzTarget21(Enum):
    CodeDeploy_20141006_GetDeployment = 'CodeDeploy_20141006.GetDeployment'


class XAmzTarget22(Enum):
    CodeDeploy_20141006_GetDeploymentConfig = 'CodeDeploy_20141006.GetDeploymentConfig'


class XAmzTarget23(Enum):
    CodeDeploy_20141006_GetDeploymentGroup = 'CodeDeploy_20141006.GetDeploymentGroup'


class XAmzTarget24(Enum):
    CodeDeploy_20141006_GetDeploymentInstance = (
        'CodeDeploy_20141006.GetDeploymentInstance'
    )


class XAmzTarget25(Enum):
    CodeDeploy_20141006_GetDeploymentTarget = 'CodeDeploy_20141006.GetDeploymentTarget'


class XAmzTarget26(Enum):
    CodeDeploy_20141006_GetOnPremisesInstance = (
        'CodeDeploy_20141006.GetOnPremisesInstance'
    )


class XAmzTarget27(Enum):
    CodeDeploy_20141006_ListApplicationRevisions = (
        'CodeDeploy_20141006.ListApplicationRevisions'
    )


class XAmzTarget28(Enum):
    CodeDeploy_20141006_ListApplications = 'CodeDeploy_20141006.ListApplications'


class XAmzTarget29(Enum):
    CodeDeploy_20141006_ListDeploymentConfigs = (
        'CodeDeploy_20141006.ListDeploymentConfigs'
    )


class XAmzTarget30(Enum):
    CodeDeploy_20141006_ListDeploymentGroups = (
        'CodeDeploy_20141006.ListDeploymentGroups'
    )


class XAmzTarget31(Enum):
    CodeDeploy_20141006_ListDeploymentInstances = (
        'CodeDeploy_20141006.ListDeploymentInstances'
    )


class XAmzTarget32(Enum):
    CodeDeploy_20141006_ListDeploymentTargets = (
        'CodeDeploy_20141006.ListDeploymentTargets'
    )


class XAmzTarget33(Enum):
    CodeDeploy_20141006_ListDeployments = 'CodeDeploy_20141006.ListDeployments'


class XAmzTarget34(Enum):
    CodeDeploy_20141006_ListGitHubAccountTokenNames = (
        'CodeDeploy_20141006.ListGitHubAccountTokenNames'
    )


class XAmzTarget35(Enum):
    CodeDeploy_20141006_ListOnPremisesInstances = (
        'CodeDeploy_20141006.ListOnPremisesInstances'
    )


class XAmzTarget36(Enum):
    CodeDeploy_20141006_ListTagsForResource = 'CodeDeploy_20141006.ListTagsForResource'


class XAmzTarget37(Enum):
    CodeDeploy_20141006_PutLifecycleEventHookExecutionStatus = (
        'CodeDeploy_20141006.PutLifecycleEventHookExecutionStatus'
    )


class XAmzTarget38(Enum):
    CodeDeploy_20141006_RegisterApplicationRevision = (
        'CodeDeploy_20141006.RegisterApplicationRevision'
    )


class XAmzTarget39(Enum):
    CodeDeploy_20141006_RegisterOnPremisesInstance = (
        'CodeDeploy_20141006.RegisterOnPremisesInstance'
    )


class XAmzTarget40(Enum):
    CodeDeploy_20141006_RemoveTagsFromOnPremisesInstances = (
        'CodeDeploy_20141006.RemoveTagsFromOnPremisesInstances'
    )


class XAmzTarget41(Enum):
    CodeDeploy_20141006_SkipWaitTimeForInstanceTermination = (
        'CodeDeploy_20141006.SkipWaitTimeForInstanceTermination'
    )


class XAmzTarget42(Enum):
    CodeDeploy_20141006_StopDeployment = 'CodeDeploy_20141006.StopDeployment'


class XAmzTarget43(Enum):
    CodeDeploy_20141006_TagResource = 'CodeDeploy_20141006.TagResource'


class XAmzTarget44(Enum):
    CodeDeploy_20141006_UntagResource = 'CodeDeploy_20141006.UntagResource'


class XAmzTarget45(Enum):
    CodeDeploy_20141006_UpdateApplication = 'CodeDeploy_20141006.UpdateApplication'


class XAmzTarget46(Enum):
    CodeDeploy_20141006_UpdateDeploymentGroup = (
        'CodeDeploy_20141006.UpdateDeploymentGroup'
    )


class Alarm(BaseModel):
    name: Optional[AlarmName] = None


class AlarmList(RootModel[List[Alarm]]):
    root: List[Alarm]


class AppSpecContent(BaseModel):
    content: Optional[RawStringContent] = None
    sha256: Optional[RawStringSha256] = None


class ApplicationInfo(BaseModel):
    applicationId: Optional[ApplicationId] = None
    applicationName: Optional[ApplicationName] = None
    computePlatform: Optional[ComputePlatform] = None
    createTime: Optional[Timestamp] = None
    gitHubAccountName: Optional[GitHubAccountTokenName] = None
    linkedToGitHub: Optional[Boolean] = None


class ApplicationsInfoList(RootModel[List[ApplicationInfo]]):
    root: List[ApplicationInfo]


class AutoRollbackConfiguration(BaseModel):
    enabled: Optional[Boolean] = None
    events: Optional[AutoRollbackEventsList] = None


class AutoScalingGroup(BaseModel):
    hook: Optional[AutoScalingGroupHook] = None
    name: Optional[AutoScalingGroupName] = None


class AutoScalingGroupList(RootModel[List[AutoScalingGroup]]):
    root: List[AutoScalingGroup]


class BatchGetApplicationsOutput(BaseModel):
    applicationsInfo: Optional[ApplicationsInfoList] = None


class BatchGetDeploymentGroupsInput(BaseModel):
    applicationName: ApplicationName
    deploymentGroupNames: DeploymentGroupsList


class BatchGetDeploymentInstancesInput(BaseModel):
    deploymentId: DeploymentId
    instanceIds: InstancesList


class BatchGetDeploymentTargetsInput(BaseModel):
    deploymentId: Optional[DeploymentId] = None
    targetIds: Optional[TargetIdList] = None


class BatchGetDeploymentsInput(BaseModel):
    deploymentIds: DeploymentsList


class BatchGetOnPremisesInstancesInput(BaseModel):
    instanceNames: InstanceNameList


class BlueInstanceTerminationOption(BaseModel):
    action: Optional[InstanceAction] = None
    terminationWaitTimeInMinutes: Optional[Duration] = None


class ContinueDeploymentInput(BaseModel):
    deploymentId: Optional[DeploymentId] = None
    deploymentWaitType: Optional[DeploymentWaitType] = None


class CreateDeploymentConfigOutput(BaseModel):
    deploymentConfigId: Optional[DeploymentConfigId] = None


class CreateDeploymentGroupOutput(BaseModel):
    deploymentGroupId: Optional[DeploymentGroupId] = None


class CreateDeploymentOutput(BaseModel):
    deploymentId: Optional[DeploymentId] = None


class DeleteDeploymentConfigInput(BaseModel):
    deploymentConfigName: DeploymentConfigName


class DeleteDeploymentGroupInput(BaseModel):
    applicationName: ApplicationName
    deploymentGroupName: DeploymentGroupName


class DeleteDeploymentGroupOutput(BaseModel):
    hooksNotCleanedUp: Optional[AutoScalingGroupList] = None


class DeleteGitHubAccountTokenInput(BaseModel):
    tokenName: Optional[GitHubAccountTokenName] = None


class DeleteGitHubAccountTokenOutput(BaseModel):
    tokenName: Optional[GitHubAccountTokenName] = None


class DeleteResourcesByExternalIdInput(BaseModel):
    externalId: Optional[ExternalId] = None


class DeploymentOverview(BaseModel):
    Failed: Optional[InstanceCount] = None
    InProgress: Optional[InstanceCount] = None
    Pending: Optional[InstanceCount] = None
    Ready: Optional[InstanceCount] = None
    Skipped: Optional[InstanceCount] = None
    Succeeded: Optional[InstanceCount] = None


class DeploymentReadyOption(BaseModel):
    actionOnTimeout: Optional[DeploymentReadyAction] = None
    waitTimeInMinutes: Optional[Duration] = None


class DeploymentStatusMessageList(RootModel[List[ErrorMessage]]):
    root: List[ErrorMessage]


class DeploymentStyle(BaseModel):
    deploymentOption: Optional[DeploymentOption] = None
    deploymentType: Optional[DeploymentType] = None


class DeregisterOnPremisesInstanceInput(BaseModel):
    instanceName: InstanceName


class Diagnostics(BaseModel):
    errorCode: Optional[LifecycleErrorCode] = None
    logTail: Optional[LogTail] = None
    message: Optional[LifecycleMessage] = None
    scriptName: Optional[ScriptName] = None


class EC2TagFilter(BaseModel):
    Key_1: Optional[Key] = Field(None, alias='Key')
    Type: Optional[EC2TagFilterType] = None
    Value_1: Optional[Value] = Field(None, alias='Value')


class EC2TagFilterList(RootModel[List[EC2TagFilter]]):
    root: List[EC2TagFilter]


class EC2TagSetList(RootModel[List[EC2TagFilterList]]):
    root: List[EC2TagFilterList]


class ECSService(BaseModel):
    clusterName: Optional[ECSClusterName] = None
    serviceName: Optional[ECSServiceName] = None


class ECSServiceList(RootModel[List[ECSService]]):
    root: List[ECSService]


class ELBInfo(BaseModel):
    name: Optional[ELBName] = None


class ELBInfoList(RootModel[List[ELBInfo]]):
    root: List[ELBInfo]


class ErrorInformation(BaseModel):
    code: Optional[ErrorCode] = None
    message: Optional[ErrorMessage] = None


class GenericRevisionInfo(BaseModel):
    deploymentGroups: Optional[DeploymentGroupsList] = None
    description: Optional[Description] = None
    firstUsedTime: Optional[Timestamp] = None
    lastUsedTime: Optional[Timestamp] = None
    registerTime: Optional[Timestamp] = None


class GetApplicationOutput(BaseModel):
    application: Optional[ApplicationInfo] = None


class GetDeploymentInstanceInput(BaseModel):
    deploymentId: DeploymentId
    instanceId: InstanceId


class GetDeploymentTargetInput(BaseModel):
    deploymentId: Optional[DeploymentId] = None
    targetId: Optional[TargetId] = None


class GetOnPremisesInstanceInput(BaseModel):
    instanceName: InstanceName


class GitHubLocation(BaseModel):
    commitId: Optional[CommitId] = None
    repository: Optional[Repository] = None


class LambdaFunctionInfo(BaseModel):
    currentVersion: Optional[Version] = None
    functionAlias: Optional[LambdaFunctionAlias] = None
    functionName: Optional[LambdaFunctionName] = None
    targetVersion: Optional[Version] = None
    targetVersionWeight: Optional[TrafficWeight] = None


class LastDeploymentInfo(BaseModel):
    createTime: Optional[Timestamp] = None
    deploymentId: Optional[DeploymentId] = None
    endTime: Optional[Timestamp] = None
    status: Optional[DeploymentStatus] = None


class LifecycleEvent(BaseModel):
    diagnostics: Optional[Diagnostics] = None
    endTime: Optional[Timestamp] = None
    lifecycleEventName: Optional[LifecycleEventName] = None
    startTime: Optional[Timestamp] = None
    status: Optional[LifecycleEventStatus] = None


class LifecycleEventList(RootModel[List[LifecycleEvent]]):
    root: List[LifecycleEvent]


class ListApplicationRevisionsInput(BaseModel):
    applicationName: ApplicationName
    deployed: Optional[ListStateFilterAction] = None
    nextToken: Optional[NextToken] = None
    s3Bucket: Optional[S3Bucket] = None
    s3KeyPrefix: Optional[S3Key] = None
    sortBy: Optional[ApplicationRevisionSortBy] = None
    sortOrder: Optional[SortOrder] = None


class ListApplicationsInput(BaseModel):
    nextToken: Optional[NextToken] = None


class ListApplicationsOutput(BaseModel):
    applications: Optional[ApplicationsList] = None
    nextToken: Optional[NextToken] = None


class ListDeploymentConfigsInput(BaseModel):
    nextToken: Optional[NextToken] = None


class ListDeploymentConfigsOutput(BaseModel):
    deploymentConfigsList: Optional[DeploymentConfigsList] = None
    nextToken: Optional[NextToken] = None


class ListDeploymentGroupsInput(BaseModel):
    applicationName: ApplicationName
    nextToken: Optional[NextToken] = None


class ListDeploymentGroupsOutput(BaseModel):
    applicationName: Optional[ApplicationName] = None
    deploymentGroups: Optional[DeploymentGroupsList] = None
    nextToken: Optional[NextToken] = None


class ListDeploymentInstancesInput(BaseModel):
    deploymentId: DeploymentId
    instanceStatusFilter: Optional[InstanceStatusList] = None
    instanceTypeFilter: Optional[InstanceTypeList] = None
    nextToken: Optional[NextToken] = None


class ListDeploymentInstancesOutput(BaseModel):
    instancesList: Optional[InstancesList] = None
    nextToken: Optional[NextToken] = None


class ListDeploymentTargetsInput(BaseModel):
    deploymentId: Optional[DeploymentId] = None
    nextToken: Optional[NextToken] = None
    targetFilters: Optional[TargetFilters] = None


class ListDeploymentTargetsOutput(BaseModel):
    nextToken: Optional[NextToken] = None
    targetIds: Optional[TargetIdList] = None


class ListDeploymentsOutput(BaseModel):
    deployments: Optional[DeploymentsList] = None
    nextToken: Optional[NextToken] = None


class ListGitHubAccountTokenNamesInput(BaseModel):
    nextToken: Optional[NextToken] = None


class ListGitHubAccountTokenNamesOutput(BaseModel):
    nextToken: Optional[NextToken] = None
    tokenNameList: Optional[GitHubAccountTokenNameList] = None


class ListOnPremisesInstancesOutput(BaseModel):
    instanceNames: Optional[InstanceNameList] = None
    nextToken: Optional[NextToken] = None


class ListTagsForResourceInput(BaseModel):
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')
    ResourceArn: Arn


class MinimumHealthyHosts(BaseModel):
    type: Optional[MinimumHealthyHostsType] = None
    value: Optional[MinimumHealthyHostsValue] = None


class RawString(BaseModel):
    content: Optional[RawStringContent] = None
    sha256: Optional[RawStringSha256] = None


class S3Location(BaseModel):
    bucket: Optional[S3Bucket] = None
    bundleType: Optional[BundleType] = None
    eTag: Optional[ETag] = None
    key: Optional[S3Key] = None
    version: Optional[VersionId] = None


class StopDeploymentOutput(BaseModel):
    status: Optional[StopStatus] = None
    statusMessage: Optional[Message] = None


class Tag(BaseModel):
    Key_1: Optional[Key] = Field(None, alias='Key')
    Value_1: Optional[Value] = Field(None, alias='Value')


class TagFilter(BaseModel):
    Key_1: Optional[Key] = Field(None, alias='Key')
    Type: Optional[TagFilterType] = None
    Value_1: Optional[Value] = Field(None, alias='Value')


class TagFilterList(RootModel[List[TagFilter]]):
    root: List[TagFilter]


class TagList(RootModel[List[Tag]]):
    root: List[Tag]


class TagResourceInput(BaseModel):
    ResourceArn: Arn
    Tags: TagList


class TargetGroupInfo(BaseModel):
    name: Optional[TargetGroupName] = None


class TargetGroupInfoList(RootModel[List[TargetGroupInfo]]):
    root: List[TargetGroupInfo]


class TargetGroupPairInfo(BaseModel):
    prodTrafficRoute: Optional[TrafficRoute] = None
    targetGroups: Optional[TargetGroupInfoList] = None
    testTrafficRoute: Optional[TrafficRoute] = None


class TargetGroupPairInfoList(RootModel[List[TargetGroupPairInfo]]):
    root: List[TargetGroupPairInfo]


class TimeBasedCanary(BaseModel):
    canaryInterval: Optional[WaitTimeInMins] = None
    canaryPercentage: Optional[Percentage] = None


class TimeBasedLinear(BaseModel):
    linearInterval: Optional[WaitTimeInMins] = None
    linearPercentage: Optional[Percentage] = None


class TimeRange(BaseModel):
    end: Optional[Timestamp] = None
    start: Optional[Timestamp] = None


class TrafficRoutingConfig(BaseModel):
    timeBasedCanary: Optional[TimeBasedCanary] = None
    timeBasedLinear: Optional[TimeBasedLinear] = None
    type: Optional[TrafficRoutingType] = None


class TriggerConfig(BaseModel):
    triggerEvents: Optional[TriggerEventTypeList] = None
    triggerName: Optional[TriggerName] = None
    triggerTargetArn: Optional[TriggerTargetArn] = None


class TriggerConfigList(RootModel[List[TriggerConfig]]):
    root: List[TriggerConfig]


class UpdateDeploymentGroupOutput(BaseModel):
    hooksNotCleanedUp: Optional[AutoScalingGroupList] = None


class AddTagsToOnPremisesInstancesInput(BaseModel):
    instanceNames: InstanceNameList
    tags: TagList


class AlarmConfiguration(BaseModel):
    alarms: Optional[AlarmList] = None
    enabled: Optional[Boolean] = None
    ignorePollAlarmFailure: Optional[Boolean] = None


class BlueGreenDeploymentConfiguration(BaseModel):
    deploymentReadyOption: Optional[DeploymentReadyOption] = None
    greenFleetProvisioningOption: Optional[GreenFleetProvisioningOption] = None
    terminateBlueInstancesOnDeploymentSuccess: Optional[
        BlueInstanceTerminationOption
    ] = None


class CloudFormationTarget(BaseModel):
    deploymentId: Optional[DeploymentId] = None
    lastUpdatedAt: Optional[Time] = None
    lifecycleEvents: Optional[LifecycleEventList] = None
    resourceType: Optional[CloudFormationResourceType] = None
    status: Optional[TargetStatus] = None
    targetId: Optional[TargetId] = None
    targetVersionWeight: Optional[TrafficWeight] = None


class CreateApplicationInput(BaseModel):
    applicationName: ApplicationName
    computePlatform: Optional[ComputePlatform] = None
    tags: Optional[TagList] = None


class CreateDeploymentConfigInput(BaseModel):
    computePlatform: Optional[ComputePlatform] = None
    deploymentConfigName: DeploymentConfigName
    minimumHealthyHosts: Optional[MinimumHealthyHosts] = None
    trafficRoutingConfig: Optional[TrafficRoutingConfig] = None


class DeploymentConfigInfo(BaseModel):
    computePlatform: Optional[ComputePlatform] = None
    createTime: Optional[Timestamp] = None
    deploymentConfigId: Optional[DeploymentConfigId] = None
    deploymentConfigName: Optional[DeploymentConfigName] = None
    minimumHealthyHosts: Optional[MinimumHealthyHosts] = None
    trafficRoutingConfig: Optional[TrafficRoutingConfig] = None


class EC2TagSet(BaseModel):
    ec2TagSetList: Optional[EC2TagSetList] = None


class ECSTaskSet(BaseModel):
    desiredCount: Optional[ECSTaskSetCount] = None
    identifer: Optional[ECSTaskSetIdentifier] = None
    pendingCount: Optional[ECSTaskSetCount] = None
    runningCount: Optional[ECSTaskSetCount] = None
    status: Optional[ECSTaskSetStatus] = None
    targetGroup: Optional[TargetGroupInfo] = None
    taskSetLabel: Optional[TargetLabel] = None
    trafficWeight: Optional[TrafficWeight] = None


class ECSTaskSetList(RootModel[List[ECSTaskSet]]):
    root: List[ECSTaskSet]


class GetDeploymentConfigOutput(BaseModel):
    deploymentConfigInfo: Optional[DeploymentConfigInfo] = None


class InstanceInfo(BaseModel):
    deregisterTime: Optional[Timestamp] = None
    iamSessionArn: Optional[IamSessionArn] = None
    iamUserArn: Optional[IamUserArn] = None
    instanceArn: Optional[InstanceArn] = None
    instanceName: Optional[InstanceName] = None
    registerTime: Optional[Timestamp] = None
    tags: Optional[TagList] = None


class InstanceInfoList(RootModel[List[InstanceInfo]]):
    root: List[InstanceInfo]


class InstanceSummary(BaseModel):
    deploymentId: Optional[DeploymentId] = None
    instanceId: Optional[InstanceId] = None
    instanceType: Optional[InstanceType] = None
    lastUpdatedAt: Optional[Timestamp] = None
    lifecycleEvents: Optional[LifecycleEventList] = None
    status: Optional[InstanceStatus] = None


class InstanceSummaryList(RootModel[List[InstanceSummary]]):
    root: List[InstanceSummary]


class InstanceTarget(BaseModel):
    deploymentId: Optional[DeploymentId] = None
    instanceLabel: Optional[TargetLabel] = None
    lastUpdatedAt: Optional[Time] = None
    lifecycleEvents: Optional[LifecycleEventList] = None
    status: Optional[TargetStatus] = None
    targetArn: Optional[TargetArn] = None
    targetId: Optional[TargetId] = None


class LambdaTarget(BaseModel):
    deploymentId: Optional[DeploymentId] = None
    lambdaFunctionInfo: Optional[LambdaFunctionInfo] = None
    lastUpdatedAt: Optional[Time] = None
    lifecycleEvents: Optional[LifecycleEventList] = None
    status: Optional[TargetStatus] = None
    targetArn: Optional[TargetArn] = None
    targetId: Optional[TargetId] = None


class ListDeploymentsInput(BaseModel):
    applicationName: Optional[ApplicationName] = None
    createTimeRange: Optional[TimeRange] = None
    deploymentGroupName: Optional[DeploymentGroupName] = None
    externalId: Optional[ExternalId] = None
    includeOnlyStatuses: Optional[DeploymentStatusList] = None
    nextToken: Optional[NextToken] = None


class ListOnPremisesInstancesInput(BaseModel):
    nextToken: Optional[NextToken] = None
    registrationStatus: Optional[RegistrationStatus] = None
    tagFilters: Optional[TagFilterList] = None


class ListTagsForResourceOutput(BaseModel):
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')
    Tags: Optional[TagList] = None


class LoadBalancerInfo(BaseModel):
    elbInfoList: Optional[ELBInfoList] = None
    targetGroupInfoList: Optional[TargetGroupInfoList] = None
    targetGroupPairInfoList: Optional[TargetGroupPairInfoList] = None


class OnPremisesTagSetList(RootModel[List[TagFilterList]]):
    root: List[TagFilterList]


class RemoveTagsFromOnPremisesInstancesInput(BaseModel):
    instanceNames: InstanceNameList
    tags: TagList


class RevisionLocation(BaseModel):
    appSpecContent: Optional[AppSpecContent] = None
    gitHubLocation: Optional[GitHubLocation] = None
    revisionType: Optional[RevisionLocationType] = None
    s3Location: Optional[S3Location] = None
    string: Optional[RawString] = None


class RevisionLocationList(RootModel[List[RevisionLocation]]):
    root: List[RevisionLocation]


class TargetInstances(BaseModel):
    autoScalingGroups: Optional[AutoScalingGroupNameList] = None
    ec2TagSet: Optional[EC2TagSet] = None
    tagFilters: Optional[EC2TagFilterList] = None


class BatchGetApplicationRevisionsInput(BaseModel):
    applicationName: ApplicationName
    revisions: RevisionLocationList


class BatchGetDeploymentInstancesOutput(BaseModel):
    errorMessage: Optional[ErrorMessage] = None
    instancesSummary: Optional[InstanceSummaryList] = None


class BatchGetOnPremisesInstancesOutput(BaseModel):
    instanceInfos: Optional[InstanceInfoList] = None


class CreateDeploymentInput(BaseModel):
    applicationName: ApplicationName
    autoRollbackConfiguration: Optional[AutoRollbackConfiguration] = None
    deploymentConfigName: Optional[DeploymentConfigName] = None
    deploymentGroupName: Optional[DeploymentGroupName] = None
    description: Optional[Description] = None
    fileExistsBehavior: Optional[FileExistsBehavior] = None
    ignoreApplicationStopFailures: Optional[Boolean] = None
    overrideAlarmConfiguration: Optional[AlarmConfiguration] = None
    revision: Optional[RevisionLocation] = None
    targetInstances: Optional[TargetInstances] = None
    updateOutdatedInstancesOnly: Optional[Boolean] = None


class DeploymentInfo(BaseModel):
    additionalDeploymentStatusInfo: Optional[AdditionalDeploymentStatusInfo] = None
    applicationName: Optional[ApplicationName] = None
    autoRollbackConfiguration: Optional[AutoRollbackConfiguration] = None
    blueGreenDeploymentConfiguration: Optional[BlueGreenDeploymentConfiguration] = None
    completeTime: Optional[Timestamp] = None
    computePlatform: Optional[ComputePlatform] = None
    createTime: Optional[Timestamp] = None
    creator: Optional[DeploymentCreator] = None
    deploymentConfigName: Optional[DeploymentConfigName] = None
    deploymentGroupName: Optional[DeploymentGroupName] = None
    deploymentId: Optional[DeploymentId] = None
    deploymentOverview: Optional[DeploymentOverview] = None
    deploymentStatusMessages: Optional[DeploymentStatusMessageList] = None
    deploymentStyle: Optional[DeploymentStyle] = None
    description: Optional[Description] = None
    errorInformation: Optional[ErrorInformation] = None
    externalId: Optional[ExternalId] = None
    fileExistsBehavior: Optional[FileExistsBehavior] = None
    ignoreApplicationStopFailures: Optional[Boolean] = None
    instanceTerminationWaitTimeStarted: Optional[Boolean] = None
    loadBalancerInfo: Optional[LoadBalancerInfo] = None
    overrideAlarmConfiguration: Optional[AlarmConfiguration] = None
    previousRevision: Optional[RevisionLocation] = None
    relatedDeployments: Optional[RelatedDeployments] = None
    revision: Optional[RevisionLocation] = None
    rollbackInfo: Optional[RollbackInfo] = None
    startTime: Optional[Timestamp] = None
    status: Optional[DeploymentStatus] = None
    targetInstances: Optional[TargetInstances] = None
    updateOutdatedInstancesOnly: Optional[Boolean] = None


class DeploymentsInfoList(RootModel[List[DeploymentInfo]]):
    root: List[DeploymentInfo]


class ECSTarget(BaseModel):
    deploymentId: Optional[DeploymentId] = None
    lastUpdatedAt: Optional[Time] = None
    lifecycleEvents: Optional[LifecycleEventList] = None
    status: Optional[TargetStatus] = None
    targetArn: Optional[TargetArn] = None
    targetId: Optional[TargetId] = None
    taskSetsInfo: Optional[ECSTaskSetList] = None


class GetApplicationRevisionInput(BaseModel):
    applicationName: ApplicationName
    revision: RevisionLocation


class GetApplicationRevisionOutput(BaseModel):
    applicationName: Optional[ApplicationName] = None
    revision: Optional[RevisionLocation] = None
    revisionInfo: Optional[GenericRevisionInfo] = None


class GetDeploymentInstanceOutput(BaseModel):
    instanceSummary: Optional[InstanceSummary] = None


class GetDeploymentOutput(BaseModel):
    deploymentInfo: Optional[DeploymentInfo] = None


class GetOnPremisesInstanceOutput(BaseModel):
    instanceInfo: Optional[InstanceInfo] = None


class ListApplicationRevisionsOutput(BaseModel):
    nextToken: Optional[NextToken] = None
    revisions: Optional[RevisionLocationList] = None


class OnPremisesTagSet(BaseModel):
    onPremisesTagSetList: Optional[OnPremisesTagSetList] = None


class RegisterApplicationRevisionInput(BaseModel):
    applicationName: ApplicationName
    description: Optional[Description] = None
    revision: RevisionLocation


class RevisionInfo(BaseModel):
    genericRevisionInfo: Optional[GenericRevisionInfo] = None
    revisionLocation: Optional[RevisionLocation] = None


class RevisionInfoList(RootModel[List[RevisionInfo]]):
    root: List[RevisionInfo]


class UpdateDeploymentGroupInput(BaseModel):
    alarmConfiguration: Optional[AlarmConfiguration] = None
    applicationName: ApplicationName
    autoRollbackConfiguration: Optional[AutoRollbackConfiguration] = None
    autoScalingGroups: Optional[AutoScalingGroupNameList] = None
    blueGreenDeploymentConfiguration: Optional[BlueGreenDeploymentConfiguration] = None
    currentDeploymentGroupName: DeploymentGroupName
    deploymentConfigName: Optional[DeploymentConfigName] = None
    deploymentStyle: Optional[DeploymentStyle] = None
    ec2TagFilters: Optional[EC2TagFilterList] = None
    ec2TagSet: Optional[EC2TagSet] = None
    ecsServices: Optional[ECSServiceList] = None
    loadBalancerInfo: Optional[LoadBalancerInfo] = None
    newDeploymentGroupName: Optional[DeploymentGroupName] = None
    onPremisesInstanceTagFilters: Optional[TagFilterList] = None
    onPremisesTagSet: Optional[OnPremisesTagSet] = None
    outdatedInstancesStrategy: Optional[OutdatedInstancesStrategy] = None
    serviceRoleArn: Optional[Role] = None
    triggerConfigurations: Optional[TriggerConfigList] = None


class BatchGetApplicationRevisionsOutput(BaseModel):
    applicationName: Optional[ApplicationName] = None
    errorMessage: Optional[ErrorMessage] = None
    revisions: Optional[RevisionInfoList] = None


class BatchGetDeploymentsOutput(BaseModel):
    deploymentsInfo: Optional[DeploymentsInfoList] = None


class CreateDeploymentGroupInput(BaseModel):
    alarmConfiguration: Optional[AlarmConfiguration] = None
    applicationName: ApplicationName
    autoRollbackConfiguration: Optional[AutoRollbackConfiguration] = None
    autoScalingGroups: Optional[AutoScalingGroupNameList] = None
    blueGreenDeploymentConfiguration: Optional[BlueGreenDeploymentConfiguration] = None
    deploymentConfigName: Optional[DeploymentConfigName] = None
    deploymentGroupName: DeploymentGroupName
    deploymentStyle: Optional[DeploymentStyle] = None
    ec2TagFilters: Optional[EC2TagFilterList] = None
    ec2TagSet: Optional[EC2TagSet] = None
    ecsServices: Optional[ECSServiceList] = None
    loadBalancerInfo: Optional[LoadBalancerInfo] = None
    onPremisesInstanceTagFilters: Optional[TagFilterList] = None
    onPremisesTagSet: Optional[OnPremisesTagSet] = None
    outdatedInstancesStrategy: Optional[OutdatedInstancesStrategy] = None
    serviceRoleArn: Role
    tags: Optional[TagList] = None
    triggerConfigurations: Optional[TriggerConfigList] = None


class DeploymentGroupInfo(BaseModel):
    alarmConfiguration: Optional[AlarmConfiguration] = None
    applicationName: Optional[ApplicationName] = None
    autoRollbackConfiguration: Optional[AutoRollbackConfiguration] = None
    autoScalingGroups: Optional[AutoScalingGroupList] = None
    blueGreenDeploymentConfiguration: Optional[BlueGreenDeploymentConfiguration] = None
    computePlatform: Optional[ComputePlatform] = None
    deploymentConfigName: Optional[DeploymentConfigName] = None
    deploymentGroupId: Optional[DeploymentGroupId] = None
    deploymentGroupName: Optional[DeploymentGroupName] = None
    deploymentStyle: Optional[DeploymentStyle] = None
    ec2TagFilters: Optional[EC2TagFilterList] = None
    ec2TagSet: Optional[EC2TagSet] = None
    ecsServices: Optional[ECSServiceList] = None
    lastAttemptedDeployment: Optional[LastDeploymentInfo] = None
    lastSuccessfulDeployment: Optional[LastDeploymentInfo] = None
    loadBalancerInfo: Optional[LoadBalancerInfo] = None
    onPremisesInstanceTagFilters: Optional[TagFilterList] = None
    onPremisesTagSet: Optional[OnPremisesTagSet] = None
    outdatedInstancesStrategy: Optional[OutdatedInstancesStrategy] = None
    serviceRoleArn: Optional[Role] = None
    targetRevision: Optional[RevisionLocation] = None
    triggerConfigurations: Optional[TriggerConfigList] = None


class DeploymentGroupInfoList(RootModel[List[DeploymentGroupInfo]]):
    root: List[DeploymentGroupInfo]


class DeploymentTarget(BaseModel):
    cloudFormationTarget: Optional[CloudFormationTarget] = None
    deploymentTargetType: Optional[DeploymentTargetType] = None
    ecsTarget: Optional[ECSTarget] = None
    instanceTarget: Optional[InstanceTarget] = None
    lambdaTarget: Optional[LambdaTarget] = None


class DeploymentTargetList(RootModel[List[DeploymentTarget]]):
    root: List[DeploymentTarget]


class GetDeploymentGroupOutput(BaseModel):
    deploymentGroupInfo: Optional[DeploymentGroupInfo] = None


class GetDeploymentTargetOutput(BaseModel):
    deploymentTarget: Optional[DeploymentTarget] = None


class BatchGetDeploymentGroupsOutput(BaseModel):
    deploymentGroupsInfo: Optional[DeploymentGroupInfoList] = None
    errorMessage: Optional[ErrorMessage] = None


class BatchGetDeploymentTargetsOutput(BaseModel):
    deploymentTargets: Optional[DeploymentTargetList] = None
